[workspace]
resolver = "2"
members = ["crates/trox", "crates/trox-cli"]

[workspace.package]
version = "0.2.1"
edition = "2024"
rust-version = "1.89"
license = "Apache-2.0"
repository = "https://github.com/thurn/trox"

[workspace.dependencies]
anyhow = "1.0"
blake3 = "1.8"
calamine = "0.36"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
data-encoding = "2.9"
globset = "0.4"
icu_locale_core = { version = "2.2", features = ["alloc"] }
indexmap = { version = "2.11", features = ["serde"] }
libc = "0.2"
rayon = "1.11"
regex = "1.11"
ron = "0.11"
rust_xlsxwriter = "0.97"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_json_canonicalizer = "0.3"
tempfile = "3.20"
thiserror = "2.0"
unicode-normalization = "0.1"
walkdir = "2.5"
