export * from "./runtime.js";
export {
  LocalizedString,
  MAX_SAFE_SELECTOR_INTEGER,
  TermId,
  counted,
  exact,
  few,
  indefinite,
  many,
  assertLocalized,
  meaning,
  one,
  opaque,
  ordinal,
  other,
  otherwise,
  plural,
  select,
  term,
  termId,
  two,
  tx,
  txa,
  when,
  zero,
  type Argument,
  type ArgumentInput,
  type BooleanArgument,
  type ExactKey,
  type IdentityDescriptor,
  type LocalizedStringWire,
  type NumericIdentityBranch,
  type NumericKey,
  type NumberArgument,
  type OpaqueArgument,
  type OrdinalKey,
  type OrdinalPattern,
  type OtherwiseIdentityBranch,
  type Pattern,
  type PluralCategory,
  type PluralKey,
  type PluralPattern,
  type PluralSelectorRecord,
  type SelectPattern,
  type SelectSelectorRecord,
  type SelectorKey,
  type SelectorRecord,
  type TermArgument,
  type TextArgument,
  type TextPattern,
  type WhenIdentityBranch,
} from "./authoring.js";
